### ISSUE TITLE
Implement Infinispan.Hotrod.Core.Marshaller<EFCacheKey>

### ISSUE THREAD

**Issue by rigazilla** [rigazilla/Infinispan.Hotrod.EFCaching#1]
marshall and unmarshall for EFCacheKey must be provided
add code [here](https://github.com/rigazilla/Infinispan.Hotrod.EFCaching/blob/39ca6af3948b018fcc647f7ffd90cc1c110b07eb/src/EFCoreSecondLevelCacheInterceptor/EFInfinispanCacheServiceProvider.cs#L41)

**Comment by NeerajGartia21** [comment]
I have started working on it.
Can you please assign it to me.

**Comment by rigazilla** [comment]
> 

sure, please provide a brief description of how are you going to proceed

**Comment by rigazilla** [comment]
> Since `EFCacheKeyMarshaller` works as a wrapper over the `Infinispan.Hotrod.Core` marshaller, so I think the type of the `EFCacheKey` can be identifies and then we can use the marshaller that are there in `Infinispan.Hotrod.Core` for marshalling and unmarshalling.
> 
> Since I'm new to C# please correct me if I'm wrong or missed something.

`Marshaller<T>` is a parametric abstract class: parametric means that you can use it as a _blueprint_ to define your specific abstract class providing the parameter: in our case we want a `Marshaller<EFCacheKey>`. Replacing T with EFCacheKey we're declaring that our class will work on EFCacheKey, so there's no need to identify type further.  
`Marshaller<EFCacheKey>` is still an abstract class which means that part of its implementation is missing so it's not possible to create new instances of that classes,  we need to first implement the missing parts in `EFCacheKeyMarshaller`.

There's no need to rely on Infinispan.Hotrod.Core code, better to just implement the two missing methods.
You can look at [Marshaller<string>](https://github.com/infinispan/Infinispan.Hotrod.Core/blob/28fe945b688ffda76ea3b87f51ca5e34c8991d2b/src/Marshaller.cs#L22-L47)

More practically, I would proceed like this:

**marshall(EFCacheKey)**
- identify all the fields that compose the `state` of an `EFCacheKey` instance (should be KeyHash, DbContext, CacheDependencies)
-  write the code that turn each field into a string
- concatenate all the strings
- turn the result into a byte[] and return it

**unmarshall(byte[])**
- turn the byte[] into a string
- split the string into part
- write the code that turn the string into each field

Sorry I thought it would be shorter... :) I hope it's clear enough, anyway please ask more.

also please move the EFCacheKeyMarshaller to a new file, so to keep things clean

I'll write a unit test for the marshaller in the next days, so you can check if your code works as expected

**Comment by rigazilla** [comment]
I've added basic unit tests in PR #4

**Comment by NeerajGartia21** [comment]
> Sorry I thought it would be shorter... :) I hope it's clear enough, anyway please ask more.

Thank you sir. It's now all clear for me.
