### ISSUE TITLE
Create an EFCore example

### ISSUE THREAD

**Issue by rigazilla** [rigazilla/Infinispan.Hotrod.EFCaching#12]
Create an EFCore example project to verify everything is working.

**Comment by HumairaSid** [comment]
Hi,
what is the example for, can you please provide more details

**Comment by rigazilla** [comment]
We need an EFCore based application to show how the Infinispan cache layer works.

I would split this issue in two steps:
1. create an example application with:
     - an entity model. No need to be complex: [this one](https://learn.microsoft.com/en-us/ef/core/#the-model) would be ok;
     - an underlying DB with a schema that fits the mode. (The DB should be easy to run both on linux and windows. maybe sqlite?)
     - a Main method that does some insert, update, select on the model.
2. integrate and enable the cache layer and show that data is correctly cached. This depends from #13, which is a TODO.

@HumairaSid let me know if you need more info

**Comment by HumairaSid** [comment]
Please assign to me, 
Just a conformation - Are we looking for DB first approach or Code first approach

**Comment by HumairaSid** [comment]
Hi, 
I have started working on it, facing some issue with EFCore sqllite "table does not exist"
My code branch https://github.com/HumairaSid/EFCoreBasicCaching

**Comment by rigazilla** [comment]
Hey nice job @HumairaSid 

you need to ensure that the schema is created on the DB. 
Easiest way to do that is adding an `EnsureCreated` method call.
I've added it in your `Program.cs`, something like:
```
...
            Console.WriteLine($"Database path: {db.DbPath}.");
            // Ensure the schema is created
            db.Database.EnsureCreated();
            // Create a menu
...
```

and seems to work. Not sure if it's the proper place, though.
More info in the doc, i.e.: https://learn.microsoft.com/en-us/ef/core/managing-schemas/ensure-created

**Comment by HumairaSid** [comment]
Sure, I am new to git hub so I am figuring out how can I contribute in this repo

**Comment by NeerajGartia21** [comment]
@HumairaSid you can refer to this [article ](https://developers.redhat.com/articles/command-line-heroes-game-pull-request#making_a_change)  for opening a pull request.

**Comment by HumairaSid** [comment]
@NeerajGartia21 I tried that for a moment I was able to see all my files there for merge, but I am still not sure that those are uploaded? Can you see any pull request from my side

**Comment by NeerajGartia21** [comment]
No, there are no pull requests at this moment.

You can follow these steps :
1. Fork [this](https://github.com/rigazilla/Infinispan.Hotrod.EFCaching) repo.
2. Clone the the forked repo to your local machine.
3. Create a new branch.
4. Add the changes, commit them and push them to your forked repo.
5. Create a pull request from there.

**Comment by HumairaSid** [comment]
Thanks, I have actually done step 4 and was missing the step to create a pull request. I hope now you can find a new pull request.
What next?

**Comment by NeerajGartia21** [comment]
Nice!
Let us review your pull request and after that it will be merged.

You can explore other issues as well.

**Comment by HumairaSid** [comment]
@NeerajGartia21 Thanks, please guide me to explore more eager to contribute and learn

**Comment by rigazilla** [comment]
@HumairaSid I've commented your PR with some change requests. Please let me know if you need more info!

**Comment by rigazilla** [comment]
closed via #14

**Comment by HumairaSid** [comment]
@rigazilla Apologies, I was unable to look into it as I accidentally injured my index finger so it was tough to type. Please let me know now what needs to be done next.

**Comment by rigazilla** [comment]
> @rigazilla Apologies, I was unable to look into it as I accidentally injured my index finger so it was tough to type. Please let me know now what needs to be done next.

@HumairaSid hope you recovered from your accident.
Do you want to have a look at #15 ?
